package net.wingress.mobivious

import kotlinx.coroutines.*
import net.wingress.mobivious.data.*
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import java.util.concurrent.TimeUnit

class CommunityTest {
    private val channel = "UC" + "a".repeat(22)
    private val post = "Ugkx_post"
    private val context = ApiContext("https://instance.test", null)
    private fun image() = JSONArray("""[{"url":"https://yt3.ggpht.com/media=s320","width":320,"height":160},{"url":"https://yt3.ggpht.com/media=s1280","width":1280,"height":640}]""")
    private fun json(attachment: JSONObject? = null) = JSONObject().put("authorId", channel).put("singlePost", true)
        .put("comments", JSONArray().put(JSONObject().put("commentId", post).put("author", "Creator")
            .put("authorId", channel).put("content", "Post text").put("contentHtml", "<b>Post text</b>")
            .put("isEdited", true).put("replyCount", 42).put("likeCount", 123).put("attachment", attachment)))
    private fun comment(id: String, replies: String = "") = Comment("Viewer", "Body", "today", 1, id = id, replyContinuation = replies)

    @Test fun channelTabsNormalizeAliasesFollowWebsiteOrderAndDeferClips() {
        val value = Channel(channel, "Creator", tabs = listOf("channels", "clips", "community", "posts", "courses", "shorts", "videos", "live", "podcasts", "releases", "playlists"))
        assertEquals(ChannelTab.entries, value.contentTabs)
        assertEquals(ChannelTab.VIDEOS, value.preferredTab())
        assertEquals(listOf(ChannelTab.POSTS), value.copy(tabs = listOf("community", "posts")).contentTabs)
        assertEquals(listOf(ChannelTab.VIDEOS), value.copy(tabs = emptyList()).contentTabs)
        assertFalse(value.copy(autoGenerated = true).contentTabs.contains(ChannelTab.PLAYLISTS))
    }
    @Test fun channelHeaderParsesOptionalMetadataAndSelectsAWideBanner() {
        val value = ApiParser.channel(JSONObject("""{"authorId":"$channel","author":"Creator","pronouns":"they/them","authorVerified":true,"ageGated":true,"description":"plain","descriptionHtml":"<b>rich</b>","authorBanners":[{"url":"wide","width":1060,"height":175},{"url":"square","width":512,"height":288}]}"""))
        assertEquals("wide", value.banner); assertEquals("they/them", value.pronouns); assertTrue(value.verified && value.ageGated)
        assertEquals("<b>rich</b>", value.descriptionHtml)
        assertFalse(ApiParser.channel(JSONObject("{}" )).verified)
        assertEquals("", ApiParser.channel(JSONObject("""{"pronouns":null,"authorBanners":null}""")).pronouns)
    }
    @Test fun postsKeepRootOwnerAndDisplayMetadataSeparateFromCommentReplies() {
        val value = PostPage.parse(json().put("continuation", "posts+/=&%"))
        val item = value.items.single()
        assertEquals(channel, item.channelId); assertEquals(post, item.id); assertEquals(42L, item.commentCount)
        assertEquals(123L, item.comment.likes); assertTrue(item.comment.edited)
        assertEquals("<b>Post text</b>", item.comment.html); assertEquals("", item.comment.replyContinuation)
        assertEquals("posts+/=&%", value.continuation)
        assertTrue(PostPage.parse(JSONObject("{}" )).items.isEmpty())
        assertNull(PostPage.parse(JSONObject("""{"comments":[{"content":"Legacy"}]}""")).items.single().commentCount)
    }
    @Test fun everyAttachmentTypeParsesWithoutDiscardingThePost() {
        val single = JSONObject().put("type", "image").put("imageThumbnails", image())
        val photos = PostPage.parse(json(single)).items.single().attachment as PostAttachment.Images
        assertEquals(1280, photos.images.single().width)
        val gallery = JSONObject().put("type", "multiImage").put("images", JSONArray().put(image()).put(image()))
        assertEquals(2, (PostAttachment.parse(gallery) as PostAttachment.Images).images.size)
        assertEquals("abcdefghijk", (PostAttachment.parse(JSONObject("""{"type":"video","videoId":"abcdefghijk","title":"Attached"}""")) as PostAttachment.VideoItem).video.id)
        assertEquals("PLattached", (PostAttachment.parse(JSONObject("""{"type":"playlist","playlistId":"PLattached","title":"List"}""")) as PostAttachment.PlaylistItem).playlist.id)
        val poll = PostAttachment.parse(JSONObject().put("type", "poll").put("totalVotes", 100)
            .put("choices", JSONArray().put(JSONObject().put("text", "Choice").put("image", image())))) as PostAttachment.Poll
        assertEquals(100L, poll.votes); assertEquals(1280, poll.choices.single().image!!.width); assertFalse(poll.quiz)
        val quiz = PostAttachment.parse(JSONObject("""{"type":"quiz","choices":[{"text":"Answer","isCorrect":true}]}""")) as PostAttachment.Poll
        assertTrue(quiz.quiz); assertEquals(true, quiz.choices.single().correct); assertNull(quiz.votes)
        listOf("""{"type":"unknown"}""", """{"type":"image"}""", """{"type":"video","error":"Unavailable"}""", """{"type":"playlist","playlistId":"../invalid"}""").forEach {
            val item = PostPage.parse(json(JSONObject(it))).items.single()
            assertEquals("Post text", item.comment.text); assertEquals(PostAttachment.Unavailable, item.attachment)
        }
    }
    @Test fun proxyImagesKeepMediaSizeAndNeverUseAnUntrustedOrigin() {
        assertEquals("https://instance.test/ggpht/media=s1280", ChannelImages.url(context.server, "https://yt3.ggpht.com/media=s1280"))
        assertEquals("https://instance.test/ggpht/banner=w1060-h175", ChannelImages.url(context.server, "//yt3.googleusercontent.com/banner=w1060-h175"))
        assertEquals("https://instance.test/ggpht/picture?size=2000", ChannelImages.url(context.server, "/ggpht/picture?size=2000"))
        listOf("https://evil.test/media", "https://user:secret@yt3.ggpht.com/media", "file:///image", "javascript:alert(1)", "https://yt3.ggpht.com:8443/media").forEach {
            assertNull(ChannelImages.url(context.server, it))
        }
        assertNull(ChannelImages.url(context.server, ""))
    }
    @Test fun postLinksResolveDirectLegacyAndHandleFormsAndRemainSeparateFromVideoLinks() {
        assertEquals(PostLink(post), PostLinks.parse("See https://www.youtube.com/post/$post", context.server))
        assertEquals(PostLink(post, channel), PostLinks.parse("${context.server}/post/$post/?ucid=$channel", context.server))
        assertEquals(PostLink(post, channel), PostLinks.parse("https://youtube.com/channel/$channel/community?lb=$post", context.server))
        assertEquals(PostLink(post), PostLinks.parse("https://youtube.com/@creator/posts?lb=$post", context.server))
        assertEquals(CommentLink.Post(PostLink(post)), CommentLinks.resolve("/post/$post", context.server, "abcdefghijk"))
        assertEquals(CommentLink.Video(VideoLink("abcdefghijk", 30)), CommentLinks.resolve("/watch?v=abcdefghijk&t=30", context.server, ""))
        assertNull(VideoLinks.parse("https://youtube.com/post/$post", context.server))
        listOf("https://youtube.com.evil.test/post/$post", "https://user:secret@youtube.com/post/$post", "https://youtube.com/post/a%2Fb", "${context.server}:8443/post/$post", "https://youtube.com/channel/$channel/community").forEach {
            assertNull(PostLinks.parse(it, context.server))
        }
    }
    @Test fun videoTabsSendSortAndOpaqueTokensAsPublicRequests() = runBlocking {
        MockWebServer().use { server ->
            server.start(); val address = server.url("/").toString().trimEnd('/')
            val api = InvidiousApi({ address }, { Account("secret", "Viewer", Long.MAX_VALUE, address) })
            ChannelTab.entries.filter { it.videoTab }.forEach { tab -> ChannelSort.entries.forEach { sort ->
                server.enqueue(MockResponse().setBody("""{"videos":[],"continuation":"next"}"""))
                assertEquals("next", api.channelVideoPage(channel, tab, " next+/=%& ", sort).continuation)
                val request = server.takeRequest()
                assertEquals("/api/v1/channels/$channel/${tab.path}", request.requestUrl!!.encodedPath)
                assertEquals(if (sort == ChannelSort.NEWEST) null else sort.apiValue, request.requestUrl!!.queryParameter("sort_by"))
                assertEquals(" next+/=%& ", request.requestUrl!!.queryParameter("continuation")); assertNull(request.getHeader("Authorization"))
            } }
        }
    }
    @Test fun playlistTabsUsePlaylistResultsAndOnlyPlaylistsHaveSorting() = runBlocking {
        MockWebServer().use { server ->
            server.start(); val api = InvidiousApi({ server.url("/").toString().trimEnd('/') }, { null })
            ChannelTab.entries.filter { it.playlistTab }.forEach { tab ->
                server.enqueue(MockResponse().setBody("""{"playlists":[{"playlistId":"PLattached","title":"List"}],"continuation":" next+/=%& "}"""))
                val result = api.channelPlaylistPage(channel, tab, sort = "oldest")
                assertEquals("PLattached", result.items.single().id)
                assertEquals(" next+/=%& ", result.continuation)
                val request = server.takeRequest()
                assertEquals("/api/v1/channels/$channel/${tab.path}", request.requestUrl!!.encodedPath)
                assertEquals(if (tab == ChannelTab.PLAYLISTS) "oldest" else null, request.requestUrl!!.queryParameter("sort_by"))
                assertNull(request.requestUrl!!.queryParameter("continuation")); assertNull(request.getHeader("Authorization"))
            }
        }
    }
    @Test fun postsRelatedChannelsDetailsAndCommentsUseTheExistingServerContracts() = runBlocking {
        MockWebServer().use { server ->
            server.start(); val address = server.url("/").toString().trimEnd('/')
            val api = InvidiousApi({ address }, { Account("secret", "Viewer", Long.MAX_VALUE, address) })
            server.enqueue(MockResponse().setBody(json().put("continuation", "next+/=%&").toString()))
            assertEquals(post, api.channelPosts(channel).items.single().id)
            val list = server.takeRequest(); assertEquals("/api/v1/channels/$channel/posts", list.path); assertNull(list.getHeader("Authorization"))
            server.enqueue(MockResponse().setBody("""{"relatedChannels":[{"authorId":"$channel","author":"Related"}],"continuation":"next"}"""))
            assertEquals(channel, api.channelRelated(channel, " next+/=%& ").items.single().id)
            val related = server.takeRequest(); assertEquals(" next+/=%& ", related.requestUrl!!.queryParameter("continuation")); assertNull(related.getHeader("Authorization"))
            server.enqueue(MockResponse().setBody(json().toString()))
            val detail = api.post(PostLink(post)); assertEquals(channel, detail.channelId)
            assertEquals("/api/v1/post/$post", server.takeRequest().path)
            server.enqueue(MockResponse().setBody(json().toString())); api.post(PostLink(post, channel))
            assertEquals(channel, server.takeRequest().requestUrl!!.queryParameter("ucid"))
            listOf("", " reply+/=%& ").forEach { token ->
                server.enqueue(MockResponse().setBody("""{"postId":"$post","comments":[{"commentId":"reply","content":"Hello"}],"continuation":"next"}"""))
                assertEquals("reply", api.postComments(CommentTarget.Post(post, detail.channelId), CommentSort.NEWEST, token).items.single().id)
                val comments = server.takeRequest()
                assertEquals("/api/v1/post/$post/comments", comments.requestUrl!!.encodedPath)
                assertEquals(channel, comments.requestUrl!!.queryParameter("ucid")); assertEquals("new", comments.requestUrl!!.queryParameter("sort_by"))
                assertEquals(token.takeIf { it.isNotBlank() }, comments.requestUrl!!.queryParameter("continuation")); assertNull(comments.getHeader("Authorization"))
            }
        }
    }
    @Test fun unavailablePostGetsAReadableFailure() = runBlocking {
        MockWebServer().use { server ->
            server.start(); val api = InvidiousApi({ server.url("/").toString().trimEnd('/') }, { null })
            server.enqueue(MockResponse().setBody("""{"comments":[]}"""))
            try { api.post(PostLink(post)); fail("Empty post accepted") } catch (e: ApiException) { assertEquals(404, e.status) }
        }
    }
    @Test fun postApiDiscardsResponsesAfterAnInstanceChange() = runBlocking {
        MockWebServer().use { server ->
            server.start(); var address = server.url("/").toString().trimEnd('/')
            val api = InvidiousApi({ address }, { null })
            server.enqueue(MockResponse().setBody(json().toString()).setBodyDelay(200, TimeUnit.MILLISECONDS))
            val request = async(Dispatchers.IO) { api.post(PostLink(post)) }
            assertNotNull(server.takeRequest(2, TimeUnit.SECONDS)); address = "https://other.test"
            try { request.await(); fail("Stale post accepted") } catch (_: CancellationException) { }
        }
    }
    @Test fun videoAndPostCommentControllersRetainIndependentTargetsAndPositions() {
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)
        try {
            val targets = mutableListOf<CommentTarget>()
            val fetch: suspend (CommentTarget, CommentSort, String, ApiContext) -> CommentPage = { target, _, _, _ ->
                targets += target; CommentPage(listOf(comment("a", "replies")))
            }
            val videos = CommentsController(scope, { context }, fetch, { it.message.orEmpty() })
            val posts = CommentsController(scope, { context }, fetch, { it.message.orEmpty() })
            videos.bind("abcdefghijk", true); videos.open(); videos.position(null, CommentPosition(2, 10))
            posts.bind(CommentTarget.Post(post, channel)); posts.open(); posts.replies(posts.state.value.feed.page.items.single())
            posts.position("a", CommentPosition(1, 20)); posts.close(); posts.open()
            assertEquals(CommentTarget.Video("abcdefghijk"), videos.state.value.target)
            assertEquals(CommentPosition(2, 10), videos.state.value.feed.position); assertTrue(videos.state.value.open)
            assertNull(posts.state.value.videoId); assertEquals(CommentPosition(1, 20), posts.state.value.thread!!.feed.position)
            assertEquals(3, targets.size); posts.back(); assertNull(posts.state.value.threadKey)
            videos.bind("abcdefghijk", false); assertTrue(posts.state.value.open)
        } finally { scope.cancel() }
    }
    @Test fun restoredPostRepliesRetryPendingLoadWithoutLosingParentOrMainPosition() {
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)
        try {
            val parent = comment("a", "reply+/=%&")
            val saved = CommentsState(CommentTarget.Post(post, channel), context, feed = CommentFeed(CommentPage(listOf(parent)), loaded = true, position = CommentPosition(2, 10)),
                threadKey = parent.key, threads = mapOf(parent.key to CommentThread(parent, CommentFeed(loading = true))))
            val tokens = mutableListOf<String>()
            val controller = CommentsController(scope, { context }, { _, _, token, _ -> tokens += token; CommentPage(listOf(comment("reply"))) }, { it.message.orEmpty() })
            controller.restore(saved); controller.open()
            assertEquals(listOf("reply+/=%&"), tokens); assertEquals("reply", controller.state.value.thread!!.feed.page.items.single().id)
            assertEquals(CommentPosition(2, 10), controller.state.value.feed.position)
            controller.restore(saved.copy(context = context.copy(generation = 1))); assertNull(controller.state.value.target)
        } finally { scope.cancel() }
    }
    @Test fun specializedFirstPagesOmitBlankTokensAndPaginationPreservesOpaqueTokens() = runBlocking {
        MockWebServer().use { server ->
            server.start(); val api = InvidiousApi({ server.url("/").toString().trimEnd('/') }, { null })
            for (token in listOf("", " \t\n", " next+/=%& ")) {
                ChannelTab.entries.filter { it.playlistTab }.forEach { tab ->
                    server.enqueue(MockResponse().setBody("""{"playlists":[]}""")); api.channelPlaylistPage(channel, tab, token)
                    assertEquals(token.takeIf { it.isNotBlank() }, server.takeRequest().requestUrl!!.queryParameter("continuation"))
                }
                server.enqueue(MockResponse().setBody("""{"comments":[]}""")); api.channelPosts(channel, token)
                assertEquals(token.takeIf { it.isNotBlank() }, server.takeRequest().requestUrl!!.queryParameter("continuation"))
                server.enqueue(MockResponse().setBody("""{"relatedChannels":[]}""")); api.channelRelated(channel, token)
                assertEquals(token.takeIf { it.isNotBlank() }, server.takeRequest().requestUrl!!.queryParameter("continuation"))
            }
        }
    }
    @Test fun latePostCommentResponsesCannotCrossTargetsSortsOrAccounts() = runBlocking {
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)
        try {
            var active = context
            val gate = CompletableDeferred<Unit>()
            val controller = CommentsController(scope, { active }, { target, sort, _, _ ->
                if ((target as CommentTarget.Post).id == post && sort == CommentSort.TOP)
                    withContext(NonCancellable) { gate.await() }
                CommentPage(listOf(comment("${target.id}-${sort.apiValue}")))
            }, { it.message.orEmpty() })
            controller.bind(CommentTarget.Post(post, channel)); controller.open()
            controller.sort(CommentSort.NEWEST)
            assertEquals("$post-new", controller.state.value.feed.page.items.single().id)
            controller.bind(CommentTarget.Post("another-post", channel)); controller.open()
            gate.complete(Unit); yield()
            assertEquals("another-post-top", controller.state.value.feed.page.items.single().id)
            active = context.copy(generation = 1); controller.bind(CommentTarget.Post("another-post", channel))
            assertFalse(controller.state.value.open); assertTrue(controller.state.value.feed.page.items.isEmpty())
        } finally { scope.cancel() }
    }
    @Test fun postReplyFailuresPreserveTheirCursorAndRepeatedContinuationsTerminate() {
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)
        try {
            var fail = true
            val tokens = mutableListOf<String>()
            val parent = comment("parent", "replies")
            val controller = CommentsController(scope, { context }, { target, _, token, _ ->
                assertEquals(CommentTarget.Post(post, channel), target); tokens += token
                when (token) {
                    "" -> CommentPage(listOf(parent), count = 20)
                    "replies" -> CommentPage(listOf(comment("r1")), "more+/=%&")
                    else -> if (fail) throw IllegalStateException("Offline") else CommentPage(listOf(comment("r1"), comment("r2")), token)
                }
            }, { it.message.orEmpty() })
            controller.bind(CommentTarget.Post(post, channel)); controller.open(); controller.replies(parent)
            controller.load(true, parent.key)
            assertEquals("more+/=%&", controller.state.value.thread!!.feed.page.continuation)
            assertEquals("Offline", controller.state.value.thread!!.feed.error)
            fail = false; controller.load(true, parent.key)
            assertEquals(listOf("", "replies", "more+/=%&", "more+/=%&"), tokens)
            assertEquals(listOf("r1", "r2"), controller.state.value.thread!!.feed.page.items.map { it.id })
            assertEquals("", controller.state.value.thread!!.feed.page.continuation)
            assertEquals(20L, controller.state.value.feed.page.count)
        } finally { scope.cancel() }
    }
}
