package net.wingress.mobivious.data

import org.json.JSONArray
import org.json.JSONObject
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

data class Video(val id: String, val title: String, val author: String = "", val channelId: String = "",
    val thumbnail: String = "", val duration: Long = 0, val views: Long = 0, val published: String = "",
    val live: Boolean = false, val indexId: String = "", val unavailable: Boolean = false, val membersOnly: Boolean = false,
    val history: HistoryMetadata? = null, val playlistIndex: Int? = null, val authorAvatar: String = "")
data class Caption(val label: String, val language: String, val url: String)
data class AudioIdentity(val id: String, val name: String, val default: Boolean?)
data class StreamFormat(val id: String, val mimeType: String, val codec: String,
    val width: Int, val height: Int, val fps: Float, val bitrate: Long, val bytes: Long,
    val audio: AudioIdentity? = null, val drc: Boolean? = null)
data class VideoDetails(val video: Video, val description: String, val dash: String, val hls: String,
    val fallback: String, val captions: List<Caption>, val recommendations: List<Video>, val formats: List<StreamFormat> = emptyList(),
    val descriptionHtml: String = "", val likes: Long? = null, val authorVerified: Boolean? = null,
    val subscribers: String = "", val upcoming: Boolean? = null, val premiereTimestamp: Long? = null,
    val listed: Boolean? = null, val genre: String = "", val genreUrl: String = "", val license: String? = null,
    val familyFriendly: Boolean? = null, val allowedRegions: List<String>? = null,
    val music: List<MusicCredit> = emptyList(), val notice: String = "")
data class MusicCredit(val song: String, val artist: String, val album: String, val license: String = "")
enum class ChannelTab(val path: String, val label: String) {
    VIDEOS("videos", "Videos"), SHORTS("shorts", "Shorts"), STREAMS("streams", "Streams"),
    PODCASTS("podcasts", "Podcasts"), RELEASES("releases", "Releases"), COURSES("courses", "Courses"),
    PLAYLISTS("playlists", "Playlists"), POSTS("posts", "Posts"), CHANNELS("channels", "Channels");
    val videoTab get() = this in listOf(VIDEOS, SHORTS, STREAMS)
    val playlistTab get() = this in listOf(PODCASTS, RELEASES, COURSES, PLAYLISTS)
}
enum class ChannelSort(val apiValue: String, val label: String) {
    NEWEST("newest", "Newest"), OLDEST("oldest", "Oldest"), POPULAR("popular", "Popular")
}
data class Channel(val id: String, val name: String, val description: String = "", val subscribers: String = "", val image: String = "",
    val tabs: List<String> = emptyList(), val banner: String = "", val verified: Boolean = false,
    val pronouns: String = "", val descriptionHtml: String = "", val ageGated: Boolean = false, val autoGenerated: Boolean = false) {
    val contentTabs: List<ChannelTab>
        get() {
            val available = tabs.map { when (val name = it.trim().lowercase()) { "community" -> "posts"; "live" -> "streams"; else -> name } }
            return ChannelTab.entries.filter { it.path in available && !(autoGenerated && it == ChannelTab.PLAYLISTS) }
                .ifEmpty { listOf(ChannelTab.VIDEOS) }
        }
    fun preferredTab(current: ChannelTab? = null): ChannelTab = current?.takeIf { it in contentTabs } ?: contentTabs.first()
}
data class Playlist(val id: String, val title: String, val count: Int, val privacy: String = "public", val description: String = "",
    val thumbnail: String = "", val author: String = "", val channelId: String = "", val owned: Boolean = false,
    val saved: Boolean = false, val seedVideoId: String? = null, val authorAvatar: String = "") {
    val mix get() = id.startsWith("RD")
    val sourceLabel get() = if (owned) "My playlist" else if (mix) "Mix" else if (id.startsWith("IV")) "Invidious playlist" else "YouTube playlist"
}
data class Page<T>(val items: List<T>, val continuation: String = "")
data class Account(val token: String, val username: String, val expiresAt: Long, val server: String)
data class ApiContext(val server: String, val account: Account?, val generation: Long = 0)
data class DeArrowIdentity(val ready: Boolean, val configured: Boolean)
data class DeArrowSubmission(val title: String, val original: Boolean, val votes: Int, val locked: Boolean, val uuid: String)

fun JSONArray.objects(): List<JSONObject> = (0 until length()).mapNotNull { optJSONObject(it) }
fun JSONObject.text(key: String, fallback: String = ""): String = if (isNull(key)) fallback else optString(key, fallback)
object ApiParser {
    fun preferences(json: JSONObject) = AccountPreferences.parse(json)
    fun dearrowSubmissions(json: JSONObject) = json.getJSONArray("titles").objects().map {
        DeArrowSubmission(it.getString("title"), it.getBoolean("original"), it.getInt("votes"), it.getBoolean("locked"), it.getString("UUID"))
    }
    fun thumbnail(json: JSONObject): String = json.optJSONArray("videoThumbnails")?.objects()?.let { images ->
        images.firstOrNull { it.text("quality") in listOf("medium", "high", "sddefault") } ?: images.firstOrNull()
    }?.text("url") ?: ""
    fun video(json: JSONObject): Video = Video(json.text("videoId", json.text("video_id")),
        json.text("title", "Unavailable video"), json.text("author", json.text("channel_name")),
        json.text("authorId", json.text("channel_id")), thumbnail(json),
        json.optLong("lengthSeconds", json.optLong("length_seconds")), json.optLong("viewCount"),
        json.text("publishedText", json.text("latest_watched")), json.optBoolean("liveNow"), json.text("indexId"), json.isNull("title") || json.text("author") == "[Deleted video]" || json.text("title") in listOf("[Deleted video]", "[Private video]"), json.opt("isMember") == true,
        playlistIndex = if (json.opt("index") is Number) json.getInt("index") else null, authorAvatar = Avatars.parse(json))
    fun videos(array: JSONArray): List<Video> = array.objects().filter { it.text("videoId", it.text("video_id")).isNotBlank() }.map(::video)
    fun details(json: JSONObject): VideoDetails = VideoDetails(video(json), json.text("description"),
        json.text("dashUrl"), json.text("hlsUrl"), json.optJSONArray("formatStreams")?.objects()?.lastOrNull()?.text("url") ?: "",
        json.optJSONArray("captions")?.objects()?.map { Caption(it.text("label"), it.text("languageCode", it.text("language_code")), it.text("url")) } ?: emptyList(),
        json.optJSONArray("recommendedVideos")?.let(::videos) ?: emptyList(),
        (json.optJSONArray("adaptiveFormats")?.objects().orEmpty() + json.optJSONArray("formatStreams")?.objects().orEmpty()).map(::streamFormat),
        descriptionHtml = json.text("descriptionHtml"), likes = (json.opt("likeCount") as? Number)?.toLong()?.takeIf { it >= 0 },
        authorVerified = json.opt("authorVerified") as? Boolean, subscribers = json.text("subCountText").takeUnless { it == "-" }.orEmpty(),
        upcoming = json.opt("isUpcoming") as? Boolean, premiereTimestamp = (json.opt("premiereTimestamp") as? Number)?.toLong()?.takeIf { it > 0 },
        listed = json.opt("isListed") as? Boolean, genre = json.text("genre"), genreUrl = json.text("genreUrl"), license = json.opt("license") as? String,
        familyFriendly = json.opt("isFamilyFriendly") as? Boolean, allowedRegions = json.optJSONArray("allowedRegions")?.let { a ->
            (0 until a.length()).mapNotNull { (a.opt(it) as? String)?.takeIf { code -> code.matches(Regex("[A-Z]{2}")) } }.distinct() },
        music = json.optJSONArray("musicTracks")?.objects().orEmpty().map { MusicCredit(it.text("song"), it.text("artist"), it.text("album"), it.text("license")) }
            .filter { it.song.isNotBlank() || it.artist.isNotBlank() || it.album.isNotBlank() }, notice = json.text("error"))
    fun streamFormat(j: JSONObject): StreamFormat {
        val size = j.text("size").split('x')
        val type = j.text("type", j.text("mimeType"))
        val codec = Regex("codecs=\"?([^\";]+)").find(type)?.groupValues?.get(1) ?: j.text("encoding")
        val audio = j.optJSONObject("audioTrack")?.let { AudioIdentity(it.text("id"), it.text("displayName"),
            if (it.opt("audioIsDefault") is Boolean) it.getBoolean("audioIsDefault") else null) }
        return StreamFormat(j.text("itag"), type.substringBefore(';').trim(), codec,
            size.getOrNull(0)?.toIntOrNull() ?: j.optInt("width"), size.getOrNull(1)?.toIntOrNull() ?: j.optInt("height"),
            j.optDouble("fps", 0.0).toFloat().takeIf { it.isFinite() && it > 0 } ?: 0f,
            j.optLong("bitrate", 0).coerceAtLeast(0), j.optLong("clen", j.optLong("contentLength", 0)).coerceAtLeast(0),
            audio, if (j.opt("isDrc") is Boolean) j.getBoolean("isDrc") else null)
    }
    fun playlist(json: JSONObject, legacyOwned: Boolean = false): Playlist {
        val id = json.text("playlistId", json.text("mixId"))
        val thumbnail = json.text("playlistThumbnail")
        val seed = sequenceOf(json.text("seedVideoId"), json.optJSONArray("videos")?.optJSONObject(0)?.text("videoId").orEmpty(),
            thumbnail.toHttpUrlOrNull()?.pathSegments?.getOrNull(1).orEmpty(), thumbnail.split('/').getOrNull(2).orEmpty(), id.removePrefix("RD"))
            .firstOrNull { it.matches(Regex("^[A-Za-z0-9_-]{11}$")) }.takeIf { id.startsWith("RD") }
        val owned = if (json.opt("isOwned") is Boolean) json.getBoolean("isOwned") else legacyOwned && id.startsWith("IV")
        return Playlist(id, json.text("title"), json.optInt("videoCount", if (id.startsWith("RD")) -1 else 0),
            json.text("privacy", if (owned) "private" else "public").lowercase(), json.text("description"),
            thumbnail, json.text("author"), json.text("authorId"), owned,
            json.optBoolean("isSaved", legacyOwned && !id.startsWith("IV")), seed, Avatars.parse(json))
    }
    fun playlists(array: JSONArray) = array.objects().filter { it.text("playlistId", it.text("mixId")).isNotBlank() }.map { playlist(it) }
    fun channel(json: JSONObject) = Channel(json.text("authorId"), json.text("author"), json.text("description"), json.text("subCountText", json.optLong("subCount").toString()),
        Avatars.parse(json),
        json.optJSONArray("tabs")?.let { tabs -> (0 until tabs.length()).mapNotNull { tabs.opt(it) as? String } } ?: emptyList(),
        json.optJSONArray("authorBanners")?.objects()?.filter { it.optInt("width") > it.optInt("height") * 2 }
            ?.minByOrNull { kotlin.math.abs(it.optInt("width") - 1060) }?.text("url").orEmpty(),
        json.opt("authorVerified") == true, json.text("pronouns"), json.text("descriptionHtml"),
        json.opt("ageGated") == true, json.opt("autoGenerated") == true)
}
